export enum ClaimStatus {
  DRAFT = 'DRAFT',
  SUBMITTED = 'SUBMITTED',
  UNDER_REVIEW = 'UNDER_REVIEW',
  PENDING_CARRIER_RESPONSE = 'PENDING_CARRIER_RESPONSE',
  APPROVED = 'APPROVED',
  REJECTED = 'REJECTED',
  RESOLVED = 'RESOLVED',
  CLOSED = 'CLOSED',
}

export enum ClaimType {
  MISSING = 'MISSING',
  DAMAGED = 'DAMAGED',
}

export enum ClaimCurrency {
  CAD = 'CAD',
  USD = 'USD',
}

export enum ClaimDocumentType {
  COST_INVOICE = "COST_INVOICE",
  DESTRUCTION = "DESTRUCTION",
  OTHER_DOCUMENT = "OTHER_DOCUMENT",
  PACKAGING_SLIP = "PACKAGING_SLIP",
  REPAIR_ESTIMATE= "REPAIR_ESTIMATE",
  SALE_INVOICE = "SALE_INVOICE",
  STATEMENT_OF_NON_REPAIRABILITY = "STATEMENT_OF_NON_REPAIRABILITY",
  PHOTO = "PHOTO"
}

export enum ClaimSource {
  SHIPMENT_STATUS_PAGE = 'SHIPMENT_STATUS_PAGE',
  CLAIMS_DASHBOARD = 'CLAIMS_DASHBOARD',
  TRACKING_ACTION_BUTTON = 'TRACKING_ACTION_BUTTON',
}