export enum ShipmentStatus {
    PICKED_UP = "PICKED_UP",
    OUT_FOR_DELIVERY = "OUT_FOR_DELIVERY",
    APPOINTMENT_REQUIRED = "APPOINTMENT_REQUIRED",
    RETURNED_TO_DOCK = "RETURNED_TO_DOCK",
    REFUSED = "REFUSED",
    DELIVERED = "DELIVERED",
    CANCELLED = "CANCELLED",
    IN_TRANSIT = "IN_TRANSIT",
    CREATED = "CREATED",
    DELAYED = "DELAYED",
    UNKNOWN = "UNKNOWN"
}