// src/modules/surcharge/surcharge.service.ts
import { Injectable, BadRequestException, NotFoundException } from '@nestjs/common';
import { EntityManager } from '@mikro-orm/core';

import { Shipment } from 'src/entities/shipment.entity';
import { Invoice } from 'src/entities/invoice.entity';
import { CreateSurchargeDto } from '../dto/create-surcharge.dto';
import { Surcharge } from 'src/entities/surcharge';
import { EmailService } from 'src/email/service/email.service';
import { SessionData } from 'express-session';
import { AddressType } from 'src/factory/base-quote';
import { Company } from 'src/entities/company.entity';


@Injectable()
export class SurchargeService {
  constructor(private readonly em: EntityManager, private readonly emailService: EmailService) {}

  async create(dto: CreateSurchargeDto, session: SessionData) {
     // 1) Resolve shipment (populate your company/user relations as needed)
    const shipment = await this.em.findOne(Shipment, { id: dto.shipmentId }, { populate: ["company", "quote", "quote.createdBy", "quote.addresses"]});

    if (!shipment?.carrier) {
      throw new BadRequestException("Invalid shipment, can't add surcharges")
    }
    
    if (!shipment) {
      throw new NotFoundException("Invalid shipmentId or you don't have required permissions");
    }

    // 2) Create invoice — invoiceNumber auto-generated by @BeforeCreate
    const invoice = new Invoice();
    invoice.shipment = shipment;
    invoice.company = this.em.getReference(Company, shipment.company.id as number);
    invoice.paid = false;
    invoice.paidBy = null;
    
    this.em.persist(invoice);

    // 3) Create surcharges and attach to invoice
    const createdSurcharges: Surcharge[] = [];
    for (const sDto of dto.surcharges) {
      const surcharge = new Surcharge();
      surcharge.shipment = shipment;
      surcharge.carrier = (shipment as any).carrier;
      surcharge.name = sDto.name;
      surcharge.amount = sDto.amount;
      surcharge.currency = sDto.currency;
      surcharge.invoice = invoice;
      surcharge.isAddedByAdmin = true;

      if(sDto.comment) surcharge.comment = sDto.comment;

      createdSurcharges.push(surcharge);
      this.em.persist(surcharge);
    }

    // 4) Flush so invoiceNumber is generated and IDs are assigned
    await this.em.flush();

    // 5) Calculate totals
    const subtotal = createdSurcharges.reduce((sum, s) => sum + Number(s.amount), 0);
    const currency = createdSurcharges[0]?.currency || 'USD';

    // 6) Build billTo from shipment relations (adjust to your entity graph)
    const companyAddress = shipment.quote.addresses.filter((addr) => addr.type === AddressType.FROM)[0];
    const user = shipment.quote.createdBy;
    const billTo = {
      name: shipment.company?.name || `${user?.firstName || ''} ${user?.lastName || ''}`.trim() || 'Customer',
      address: companyAddress.addressBookEntry?.address?.address1 || '',
      city: companyAddress.addressBookEntry?.address?.city || '',
      province: companyAddress.addressBookEntry?.address?.state || '',
      postalCode: companyAddress.addressBookEntry?.address?.postalCode || '',
    };

    // 7) Fire email event
    this.emailService.sendInvoiceEmail({
      to: user?.email || 'billing@customer.com',
      subject: `Invoice ${invoice.invoiceNumber}`,
      template: 'surcharge-invoice',
      context: {
        invoiceNumber: invoice.invoiceNumber,
        invoiceDate: (invoice.createdAt as Date).toLocaleDateString('en-CA'),
        dueDate: invoice.dueDate?.toLocaleDateString('en-CA'),
        billTo,
        surcharges: createdSurcharges.map(s => ({
          name: s.name,
          amount: Number(s.amount),
          currency: s.currency,
        })),
        subtotal,
        total: subtotal,
        currency,
      }
    });

    return {
      message: 'Invoice created successfully',
      invoice,
      surcharges: createdSurcharges,
    };
  }
}